name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  ACR_NAME: collectionsgenericregistry
  ACR_LOGIN_SERVER: collectionsgenericregistry.azurecr.io
  IMAGE_NAME: collections-generic-pipekat-image
  RESOURCE_GROUP: DGEM-Collections-Generic-Dev
  CONTAINERAPP_NAME: collections-generic-pipekat-demo


jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name collectionsgenericregistry
 
      - name: Build Docker image
        run: |
          docker build -t collectionsgenericregistry.azurecr.io/collections-generic-pipekat-image:${{ github.run_number }} .
 
      - name: Push Docker image
        run: |
          docker push collectionsgenericregistry.azurecr.io/collections-generic-pipekat-image:${{ github.run_number }}


    # # Deploy to Azure Container App
    # - name: Deploy to Azure Container Apps
    #   run: |
    #     az containerapp update \
    #       --name ${{ env.CONTAINERAPP_NAME }} \
    #       --resource-group ${{ env.RESOURCE_GROUP }} \
    #       --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}